### Load tensorflow

In [0]:
import tensorflow as tf

### Enable Eager Execution if you are using tensorflow 1.x

In [0]:
#Enable Eager Execution
tf.enable_eager_execution()

### Collect Data

In [0]:
import pandas as pd

In [0]:
data = pd.read_csv('prices.csv')

### Check all columns in the dataset

In [39]:
data.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

### Drop columns `date` and  `symbol`

In [0]:
data.drop(columns=['date', 'symbol'], inplace=True)

In [41]:
data.head()

open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set

In [0]:
data_1000=data.head(100)

### Convert Float64 to Float32

In [43]:
data_1000.astype('float32')

open       close         low        high     volume
0   123.430000  125.839996  122.309998  126.250000  2163600.0
1   125.239998  119.980003  119.940002  125.540001  2386400.0
2   116.379997  114.949997  114.930000  119.739998  2489500.0
3   115.480003  116.620003  113.500000  117.440002  2006300.0
4   117.010002  114.970001  114.089996  117.330002  1408600.0
5   115.510002  115.550003  114.500000  116.059998  1098000.0
6   116.459999  112.849998  112.589996  117.070000   949600.0
7   113.510002  114.379997  110.050003  115.029999   785300.0
8   113.330002  112.529999  111.919998  114.879997  1093700.0
9   113.660004  110.379997  109.870003  115.870003  1523500.0
10  109.059998  109.300003  108.320000  111.599998  1653900.0
11  109.730003  110.000000  108.320000  110.580002   944300.0
12  111.879997  111.949997  110.190002  112.949997   744900.0
13  111.320000  110.120003  110.000000  114.629997   703800.0
14  110.419998  111.000000  107.300003  111.400002   563100.0
15  110.769997  110.709999  109.019997  112.570000   896100.0
16  110.900002  112.580002  109.900002  112.970001   680400.0
17  113.349998  114.470001  111.669998  114.589996   749900.0
18  114.000000  114.500000  112.900002  114.849998   574200.0
19  113.250000  110.559998  109.750000  113.860001   694800.0
20  113.379997  114.050003  109.639999  114.639999   896300.0
21  114.080002  115.709999  114.080002  116.320000   956300.0
22  115.120003  114.019997  109.709999  116.489998   997100.0
23  113.300003  111.160004  110.459999  113.300003  1200500.0
24  111.169998  110.650002  109.639999  112.110001  1725200.0
25  106.730003  107.519997  106.360001  112.110001  1946000.0
26  105.629997  107.129997  104.110001  109.260002  1319500.0
27  108.559998  107.839996  107.070000  109.430000   922400.0
28  109.110001  110.769997  107.010002  111.300003  1185100.0
29  110.830002  111.239998  107.970001  112.110001   921500.0
..         ...         ...         ...         ...        ...
70  117.500000  118.449997  115.930000  118.800003   939300.0
71  118.320000  121.260002  117.510002  121.269997   735500.0
72  121.349998  121.680000  121.169998  122.419998   924600.0
73  121.099998  122.309998  121.019997  122.459999   658800.0
74  122.610001  123.010002  121.930000  124.129997  1055400.0
75  123.480003  123.790001  122.580002  124.739998   695300.0
76  123.199997  123.300003  122.169998  124.000000   460000.0
77  123.959999  124.400002  123.160004  124.459999   532900.0
78  124.589996  124.690002  123.129997  124.989998   462600.0
79  123.540001  124.150002  122.680000  124.620003   910700.0
80  123.800003  124.900002  122.050003  125.169998   889600.0
81  125.440002  125.959999  124.800003  126.739998   734700.0
82  124.559998  126.269997  123.660004  126.430000  1304800.0
83  125.389999  126.559998  124.970001  126.779999  1597300.0
84  126.660004  127.660004  126.199997  127.790001  1917500.0
85  127.360001  121.559998  121.239998  127.360001  3221500.0
86  122.279999  123.440002  121.199997  123.639999   919800.0
87  123.889999  125.510002  122.809998  125.989998  1991600.0
88  125.699997  124.209999  124.070000  125.940002   594800.0
89  124.440002  123.889999  122.010002  124.570000   475800.0
90  123.910004  122.970001  122.750000  126.269997   715100.0
91  123.120003  123.910004  122.870003  124.610001   528500.0
92  123.400002  123.410004  121.139999  124.169998   580000.0
93  123.220001  125.269997  122.519997  125.400002   629700.0
94  124.519997  125.120003  122.690002  125.470001   598200.0
95  125.150002  125.570000  123.900002  125.769997   816700.0
96  125.480003  125.949997  124.760002  126.230003   640800.0
97  126.129997  126.620003  125.169998  127.080002   761100.0
98  127.080002  126.459999  125.940002  128.059998   462100.0
99  126.360001  126.610001  125.419998  126.980003   627000.0

[100 rows x 5 columns]

### Divide the data into train and test sets

In [0]:
from sklearn.preprocessing import Normalizer

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
#data_1000.head()
X = data_1000.drop(columns=['close'])
y = data_1000.close

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [0]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
y_train = y_train.astype('float32')


### Normalize Train and Test Data 

In [0]:
transformer = Normalizer()
train_x = transformer.fit_transform(X_train)
test_x = transformer.fit_transform(X_test)
#y_train = transformer.fit_transform(y_train)

## Building the graph in tensorflow

2.Define Weights and Bias

In [0]:
w = tf.zeros(shape=(4,1))
b = tf.zeros(shape=(1))

In [58]:
train_x.shape

(80, 4)

In [59]:
test_x.shape

(20, 4)

In [66]:
y_train.shape

(80,)

In [0]:
import numpy as np

In [0]:
y_train = np.array(y_train)

3.Prediction

In [0]:
def prediction(x, w, b):
    
    xw_matmul = tf.matmul(x, w)
    y = tf.add(xw_matmul, b)
    
    return y

4.Loss (Cost) Function [Mean square error]

In [0]:
def loss(y_actual, y_predicted):
    
    diff = y_actual - y_predicted
    sqr = tf.square(diff)
    avg = tf.reduce_mean(sqr)
    
    return avg

5.GradientDescent Optimizer to minimize Loss [GradientDescentOptimizer]

In [0]:
def train(x, y_actual, w, b, learning_rate=0.01):
    
    #Record mathematical operations on 'tape' to calculate loss
    with tf.GradientTape() as t:
        
        t.watch([w,b])
        
        current_prediction = prediction(x, w, b)
        current_loss = loss(y_actual, current_prediction)
    
    #Calculate Gradients for Loss with respect to Weights and Bias
    dw, db = t.gradient(current_loss,[w, b])
    
    #Update Weights and Bias
    w = w - learning_rate*dw
    b = b - learning_rate*db
    
    return w, b

## Execute the Graph for 100 epochs and observe the loss

In [81]:
#Train for 100 Steps
for i in range(100):
    
    w, b = train(train_x, y_train, w, b, learning_rate=0.01)
    print('Current Loss on iteration', i, 
          loss(y_train, prediction(train_x, w, b)).numpy())

Current Loss on iteration 0 11865.057
Current Loss on iteration 1 10937.174
Current Loss on iteration 2 10082.035
Current Loss on iteration 3 9293.941
Current Loss on iteration 4 8567.634
Current Loss on iteration 5 7898.2686
Current Loss on iteration 6 7281.3813
Current Loss on iteration 7 6712.8574
Current Loss on iteration 8 6188.9062
Current Loss on iteration 9 5706.033
Current Loss on iteration 10 5261.017
Current Loss on iteration 11 4850.89
Current Loss on iteration 12 4472.9175
Current Loss on iteration 13 4124.5776
Current Loss on iteration 14 3803.5476
Current Loss on iteration 15 3507.6865
Current Loss on iteration 16 3235.0212
Current Loss on iteration 17 2983.7324
Current Loss on iteration 18 2752.145
Current Loss on iteration 19 2538.7134
Current Loss on iteration 20 2342.0154
Current Loss on iteration 21 2160.7385
Current Loss on iteration 22 1993.6735
Current Loss on iteration 23 1839.7067
Current Loss on iteration 24 1697.8103
Current Loss on iteration 25 1567.0397
Cur

### Get the shapes and values of W and b

In [76]:
print(w.shape)
print(b.shape)

(4, 1)
(1,)


In [85]:
print(w.numpy())

[[9.266107e-03]
 [9.151972e-03]
 [9.364573e-03]
 [5.806641e+01]]


In [84]:
print(b.numpy())

[58.066418]


### Linear Classification using Keras

### Building the simple Neural Network in Keras with one neuron in the dense hidden layer.
#### Use Mean square error as loss function and sgd as optimizer

In [0]:
#Initialize Sequential Graph (model)
model = tf.keras.Sequential()

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(1, input_shape=(4,)))

#Compile the model - add Loss and Gradient Descent optimizer
model.compile(optimizer='sgd', loss='mse')

### Execute the model

In [87]:
model.fit(train_x, y_train, epochs=100)

Epoch 1/100
80/80 [==============================] - 0s 2ms/sample - loss: 12893.2730
Epoch 2/100
80/80 [==============================] - 0s 98us/sample - loss: 10102.8164
Epoch 3/100
80/80 [==============================] - 0s 105us/sample - loss: 7912.7998
Epoch 4/100
80/80 [==============================] - 0s 102us/sample - loss: 6198.0533
Epoch 5/100
80/80 [==============================] - 0s 105us/sample - loss: 4855.0719
Epoch 6/100
80/80 [==============================] - 0s 157us/sample - loss: 3803.2457
Epoch 7/100
80/80 [==============================] - 0s 110us/sample - loss: 2982.7021
Epoch 8/100
80/80 [==============================] - 0s 145us/sample - loss: 2339.4683
Epoch 9/100
80/80 [==============================] - 0s 120us/sample - loss: 1835.5808
Epoch 10/100
80/80 [==============================] - 0s 121us/sample - loss: 1443.8775
Epoch 11/100
80/80 [==============================] - 0s 119us/sample - loss: 1136.4241
Epoch 12/100
80/80 [======================

In [88]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 5         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [89]:
model.get_weights()

[array([[ 0.4351939 ],
        [-0.29911602],
        [ 0.36040324],
        [59.480927  ]], dtype=float32), array([58.50455], dtype=float32)]

### Classification using Keras 

### Load the given Iris data using pandas (Iris.csv)

In [125]:
iris_data = pd.read_csv('/content/drive/My Drive/ml_data/Iris.csv')
iris_data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Splitting the data into feature set and target set

In [0]:
X_i = iris_data.drop(columns=['Id','Species'])
y_i = iris_data.Species

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [127]:
y_i.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [128]:
y_i.shape

(150,)

In [129]:
y_i

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17        Iris-setosa
18        Iris-setosa
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25        Iris-setosa
26        Iris-setosa
27        Iris-setosa
28        Iris-setosa
29        Iris-setosa
            ...      
120    Iris-virginica
121    Iris-virginica
122    Iris-virginica
123    Iris-virginica
124    Iris-virginica
125    Iris-virginica
126    Iris-virginica
127    Iris-virginica
128    Iris-virginica
129    Iris-virginica
130    Iris-virginica
131    Iris-virginica
132    Iris-virginica
133    Iris-virginica
134    Iri

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
from sklearn.preprocessing import OneHotEncoder

In [0]:
y_lc = LabelEncoder().fit(y_i).transform(y_i)

In [0]:
y_lc = pd.get_dummies(y_lc).values

In [144]:
y_lc

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [145]:
y_lc.shape

(150, 3)

In [132]:
y_lc

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Divide the dataset into Training and test (70:30)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X_i, y_lc, test_size=0.2, random_state=40)

### Model
Build the model with following layers: <br>
1. First dense layer with 10 neurons with input shape 4 (according to the feature set) <br>
2. Second Dense layer with 8 neurons <br>
3. Output layer with 3 neurons with softmax activation (output layer, 3 neurons as we have 3 classes) <br>
4. Use SGD and categorical_crossentropy loss 

In [0]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Add Dense layer for prediction - Keras declares weights and bias automatically
model.add(tf.keras.layers.Dense(10, input_shape=(4,)))


model.add(tf.keras.layers.Dense(8, input_shape=(4,)))

#Add Dense Layer which provides 10 Outputs after applying softmax
model.add(tf.keras.layers.Dense(3, activation='softmax'))

#Comile the model
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])


In [0]:
#tf.keras.utils.to_categorical

### Fitting the model and predicting 

In [148]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_8 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 27        
Total params: 165
Trainable params: 165
Non-trainable params: 0
_________________________________________________________________


In [150]:
model.fit(X_train,y_train,          
          validation_data=(X_test,y_test),
          epochs=100,
          batch_size=32)

Train on 120 samples, validate on 30 samples
Epoch 1/100
120/120 [==============================] - 0s 1ms/sample - loss: 3.1580 - acc: 0.3083 - val_loss: 1.8549 - val_acc: 0.2667
Epoch 2/100
120/120 [==============================] - 0s 130us/sample - loss: 1.5075 - acc: 0.3417 - val_loss: 1.3289 - val_acc: 0.4000
Epoch 3/100
120/120 [==============================] - 0s 196us/sample - loss: 1.1916 - acc: 0.4000 - val_loss: 1.1092 - val_acc: 0.4000
Epoch 4/100
120/120 [==============================] - 0s 134us/sample - loss: 0.9492 - acc: 0.5583 - val_loss: 0.9680 - val_acc: 0.4667
Epoch 5/100
120/120 [==============================] - 0s 130us/sample - loss: 0.8490 - acc: 0.6583 - val_loss: 0.8965 - val_acc: 0.5333
Epoch 6/100
120/120 [==============================] - 0s 125us/sample - loss: 0.8203 - acc: 0.6333 - val_loss: 0.8407 - val_acc: 0.6333
Epoch 7/100
120/120 [==============================] - 0s 121us/sample - loss: 0.7534 - acc: 0.6750 - val_loss: 0.8191 - val_acc: 0.633

### Report Accuracy of the predicted values

In [151]:
pred = model.predict(X_test[15:20])
pred

array([[2.0939871e-04, 1.6454205e-01, 8.3524859e-01],
       [1.3777600e-03, 4.3343094e-01, 5.6519127e-01],
       [7.1040407e-04, 3.6852077e-01, 6.3076884e-01],
       [5.8368417e-03, 8.4125382e-01, 1.5290940e-01],
       [3.2661296e-02, 8.1679761e-01, 1.5054116e-01]], dtype=float32)

In [152]:
y_test[15:20]

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0]], dtype=uint8)

In [153]:
model.evaluate(X_test, y_test)

30/30 [==============================] - 0s 150us/sample - loss: 0.2304 - acc: 0.9333


[0.23035936057567596, 0.93333334]